# Generated by Django 4.2.19 on 2025-02-15 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_product_order_pr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.products'),
        ),
    ]
