# Generated by Django 4.2.19 on 2025-02-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_alter_shippingaddress_shipping_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_address1',
            field=models.TextField(max_length=15000),
        ),
    ]
